Unnest the auxiliary function flatten()
This avoids the following error encountered with some version(s) of Python,
specifically 2.7.6:

 SyntaxError: unqualified exec is not allowed in function 'processFile' it contains a nested function with free variables

(cherry picked from commit 5c3567327aec97156640051073454ead9263e7ec)

Preparing to do it RIGHT THIS TIME....